gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-srcset

# top level stuff you probably don't need to touch
highlighter: rouge
#markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: pretty
paginate: 5
port: 3000
safe: false

# edit here to achieve your personal greatness
url: https://emmawinston.me
baseurl: 
title: Emma Winston
author: Emma Winston
description: Emma Winston - academic and musician based in London UK.
avatar: profile.png
email: e.winston@gold.ac.uk
github: emmawinston # username
twitter: deer_ful
linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
